### ISSUE TITLE
File name meaning

### ISSUE THREAD

**Issue by zhangpicb** [aanderson54/Loupe_BrainTF#2]
Hi @aanderson54 @jloupe 

Thanks for the great resource!
Brain TF bed file downloaded from  https://www.synapse.org/Synapse:syn51942384.5/datasets/
DLPFC tissue TF ASH2L have 4 files,DLPFC-NEG mean not neuron cells? what's the difference between Output_idr.optimal_peak.regionPeak.gz and Output_ppr.IDR0.05.filt.narrowPeak.gz?

ASH2L_DLPFC-NEG_Output_idr.optimal_peak.regionPeak.gz
ASH2L_DLPFC-NEUN_Output_idr.optimal_peak.regionPeak.gz
ASH2L_DLPFC-OLIG_Output_idr.optimal_peak.regionPeak.gz
ASH2L_DLPFC_Output_ppr.IDR0.05.filt.narrowPeak.gz

Thanks in advanced!

**Comment by aanderson54** [comment]
The first three files listed are from sorted DLPFC tissue. NEUN is NeuN+ (neurons), OLIG is Olig2+ (oligodendrocytes), and NEG is NeuN- and Olig2- (mostly astrocytes/microglia). The last file is from bulk tissue. 

The regionPeak and narrowPeak file types are equivalent. The naming strategy changed in the updated version of the ENCODE ChIP-seq pipeline, but the peaks are called using the same method. 

Please let me know if you have any other questions!

Ashlyn

**Comment by zhangpicb** [comment]
Thanks again!
